fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    ruby: "git://github.com/puppetlabs/puppetlabs-ruby.git"
    remote_file: "git://github.com/lwf/puppet-remote_file.git"
  symlinks:
    datadog_agent: "#{source_dir}"
